{ lib, pkgs, ... }:
{
  wayland.windowManager.hyprland.settings = {
    windowrulev2 = [
      "opacity 0.90 0.90,class:^(librewolf)$"
      "opacity 0.80 0.80,class:^(Steam)$"
      "opacity 0.80 0.80,class:^(steam)$"
      "opacity 0.80 0.80,class:^(steamwebhelper)$"
      "opacity 0.80 0.80,class:^(Spotify)$"
      "opacity 0.80 0.80,initialTitle:^(Spotify Premium)$"
      "opacity 0.80 0.80,initialTitle:^(Spotify Free)$"
      "opacity 0.80 0.80,class:^(code-oss)$"
      "opacity 0.80 0.80,class:^(Code)$"
      "opacity 0.80 0.80,class:^(code-url-handler)$"
      "opacity 0.80 0.80,class:^(code-insiders-url-handler)$"
      "opacity 0.80 0.80,class:^(kitty)$"
      "opacity 0.80 0.80,class:^(org.kde.dolphin)$"
      "opacity 0.80 0.80,class:^(org.kde.ark)$"
      "opacity 0.80 0.80,class:^(nwg-look)$"
      "opacity 0.80 0.80,class:^(qt5ct)$"
      "opacity 0.80 0.80,class:^(qt6ct)$"
      "opacity 0.80 0.80,class:^(kvantummanager)$"
      "opacity 0.80 0.80,class:^(waypaper)$"
      "opacity 0.80 0.80,class:^(org.pulseaudio.pavucontrol)$"

      "opacity 0.90 0.90,class:^(com.github.rafostar.Clapper)$"
      "opacity 0.80 0.80,class:^(com.github.tchx84.Flatseal)$"
      "opacity 0.80 0.80,class:^(hu.kramo.Cartridges)$"
      "opacity 0.80 0.80,class:^(com.obsproject.Studio)$"
      "opacity 0.80 0.80,class:^(gnome-boxes)$ # Boxes-Gtk"
      "opacity 0.80 0.80,class:^(net.davidotek.pupgui2)$"
      "opacity 0.80 0.80,class:^(yad)$"
      "opacity 0.80 0.80,class:^(signal)$"
      "opacity 0.80 0.80,class:^(io.github.alainm23.planify)$"
      "opacity 0.80 0.80,class:^(io.gitlab.theevilskeleton.Upscaler)$"
      "opacity 0.80 0.80,class:^(com.github.unrud.VideoDownloader)$"
      "opacity 0.80 0.80,class:^(lutris)$"

      "opacity 0.80 0.70,class:^(pavucontrol)$"
      "opacity 0.80 0.70,class:^(blueman-manager)$"
      "opacity 0.80 0.70,class:^(nm-applet)$"
      "opacity 0.80 0.70,class:^(nm-connection-editor)$"
      "opacity 0.80 0.70,class:^(org.kde.polkit-kde-authentication-agent-1)$"

      "float,title:^(Picture-in-Picture)$"
      "float,class:^(librewolf)$,title:^(Library)$"
      "float,class:^(vlc)$"
      "float,class:^(kvantummanager)$"
      "float,class:^(qt5ct)$"
      "float,class:^(qt6ct)$"
      "float,class:^(nwg-look)$"
      "float,class:^(org.kde.ark)$"
      "float,class:^(org.pulseaudio.pavucontrol)$"
      "float,class:^(com.github.rafostar.Clapper)$ # Clapper-Gtk"
      "float,class:^(net.davidotek.pupgui2)$ # ProtonUp-Qt"
      "float,class:^(yad)$ # Protontricks-Gtk"
      "float,class:^(eog)$ # Imageviewer-Gtk"
      "float,class:^(io.github.alainm23.planify)$ # planify-Gtk"
      "float,class:^(io.gitlab.theevilskeleton.Upscaler)$ # Upscaler-Gtk"
      "float,class:^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gkk"
      "float,class:^(pavucontrol)$"
      "float,class:^(blueman-manager)$"
      "float,class:^(nm-applet)$"
      "float,class:^(nm-connection-editor)$"
      "float,class:^(org.kde.polkit-kde-authentication-agent-1)$"
      "opacity 0.80 0.80,class:^(org.freedesktop.impl.portal.desktop.gtk)$"
      "opacity 0.80 0.80,class:^(org.freedesktop.impl.portal.desktop.hyprland)$"

      "pseudo, class:^(fcitx)$"
    ];

    layerrule = [
      "blur,rofi"
      "ignorezero,rofi"
      "blur,notifications"
      "ignorezero,notifications"
      "blur,swaync-notification-window"
      "ignorezero,swaync-notification-window"
      "blur,swaync-control-center"
      "ignorezero,swaync-control-center"
      "blur,logout_dialog"
      "blur,waybar"
      "ignorezero,waybar"
    ];
  };
}
